import { app, BrowserWindow, ipcMain, shell } from 'electron'
import { join } from 'path'
import { existsSync } from 'fs'
import { autoUpdater } from 'electron-updater'
import { getPrintStatus, savePrintSettings, emailShipments } from './email'

let mainWindow: BrowserWindow | null = null

function createWindow(): void {
  // In dev the packaged exe icon doesn't apply, so point the window at the
  // source PNG. In the installed app this path is absent and the embedded
  // executable icon (generated by electron-builder) is used instead.
  const devIcon = join(process.cwd(), 'build', 'icon.png')

  mainWindow = new BrowserWindow({
    width: 1200,
    height: 800,
    minWidth: 940,
    minHeight: 620,
    show: false,
    autoHideMenuBar: true,
    backgroundColor: '#0f1226',
    title: 'Inventory',
    ...(existsSync(devIcon) ? { icon: devIcon } : {}),
    webPreferences: {
      preload: join(__dirname, '../preload/index.js'),
      sandbox: false,
      contextIsolation: true
    }
  })

  mainWindow.on('ready-to-show', () => mainWindow?.show())

  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    shell.openExternal(url)
    return { action: 'deny' }
  })

  // electron-vite injects this env var in dev; load the built file in prod.
  const devUrl = process.env['ELECTRON_RENDERER_URL']
  if (devUrl) {
    mainWindow.loadURL(devUrl)
  } else {
    mainWindow.loadFile(join(__dirname, '../renderer/index.html'))
  }
}

app.whenReady().then(() => {
  createWindow()

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })

  // Auto-update: only check in packaged builds.
  if (app.isPackaged) {
    autoUpdater.checkForUpdatesAndNotify().catch(() => {})
  }
})

// Set while installing an update so window-all-closed doesn't quit the app
// before electron-updater has spawned the installer.
let quittingForUpdate = false

app.on('window-all-closed', () => {
  if (quittingForUpdate) return
  if (process.platform !== 'darwin') app.quit()
})

// Expose app version to the renderer.
ipcMain.handle('app:getVersion', () => app.getVersion())

// Manual "check for updates" trigger from the UI.
ipcMain.handle('updates:check', async () => {
  if (!app.isPackaged) return { status: 'dev', message: 'Updates run only in the installed app.' }
  try {
    const result = await autoUpdater.checkForUpdates()
    return { status: 'ok', version: result?.updateInfo?.version ?? null }
  } catch (e) {
    return { status: 'error', message: String(e) }
  }
})

// Stream update lifecycle + download progress to the renderer on one channel.
function sendUpdateStatus(payload: Record<string, unknown>): void {
  mainWindow?.webContents.send('updates:status', payload)
}

autoUpdater.on('checking-for-update', () => sendUpdateStatus({ state: 'checking' }))
autoUpdater.on('update-available', (info) =>
  sendUpdateStatus({ state: 'available', version: info?.version })
)
autoUpdater.on('update-not-available', () => sendUpdateStatus({ state: 'none' }))
autoUpdater.on('download-progress', (p) =>
  sendUpdateStatus({ state: 'downloading', percent: Math.round(p?.percent ?? 0) })
)
autoUpdater.on('update-downloaded', (info) =>
  sendUpdateStatus({ state: 'downloaded', version: info?.version })
)
autoUpdater.on('error', (err) => sendUpdateStatus({ state: 'error', message: String(err) }))

// Quit and install the downloaded update (triggered by the Restart button).
// quitAndInstall(isSilent=true, isForceRunAfter=true): install silently and
// relaunch — without this the assisted installer makes the app appear to just
// close without updating.
ipcMain.handle('updates:quitAndInstall', () => {
  quittingForUpdate = true
  setImmediate(() => autoUpdater.quitAndInstall(true, true))
})

// ---- Printer email (Epson Email Print) ----
ipcMain.handle('print:getSettings', () => getPrintStatus())
ipcMain.handle('print:saveSettings', (_e, input) => savePrintSettings(input))
ipcMain.handle('print:email', (_e, payload) => emailShipments(payload))
